services:
    db:
        image: mysql
        ports: 
            - 3376:3306
        command: --default-authentication-plugin=caching_sha2_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_DB}
            MYSQL_PASSWORD: ${MYSQL_PW}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
        env_file: .env
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        env_file: .env
        ports: 
            - 8090:80
        volumes:
            - www-data:/var/www/html
            - ./media:/var/www/html/filestore
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        env_file: .env
        ports:
            - 8000:80
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_DB}
            MYSQL_PASSWORD: ${MYSQL_PW}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
volumes:
    persistent:
    www-data:
networks:
    default: