services:
    db:
        image: mysql
        ports: 
            - 3376:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: resource
            MYSQL_USER: resource
            MYSQL_PASSWORD: resource
            MYSQL_ROOT_PASSWORD: resource
        env_file: .env
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        env_file: .env
        ports: 
            - 8090:80
        volumes:
            - www-data:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        env_file: .env
        ports:
            - 8000:80
        environment:
            MYSQL_DATABASE: resource
            MYSQL_USER: resource
            MYSQL_PASSWORD: resource
            MYSQL_ROOT_PASSWORD: resource
volumes:
    persistent:
    www-data:
networks:
    default: